name: Publish release packages
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Build the wheel and source tarball
        run: uv build
      - name: Store dist packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Test publishing to testpypi
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: testpypi
      url: https://test.pypi.org/p/topen
    permissions:
      id-token: write
    steps:
      - name: Grab dist files
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Send off to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish dist to pypi
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/topen
    permissions:
      id-token: write
    steps:
      - name: Grab dist files
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Send off to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1

  create-release:
    name: Create github release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          branch: main
